#ifndef __BOOTLOADER_PROJECT_CONFIG_H__
#define __BOOTLOADER_PROJECT_CONFIG_H__

#define BOOTLOADER_UART_BAUD 115200
#define BOOTLOADER_RESPONSE_DELAY_MS 20

#define BOOTLOADER_TIMEOUT_MS 5000

//#define BOOTLOADER_USE_USER_DATA

#define BOOTLOADER_APP_BEGIN   0x08003000UL
#define BOOTLOADER_APP_LENGTH  53248UL

#define BOOTLOADER_DEVICE_ID_STRING "gd32e230c8-rs485-bootloader"

#endif
